# Configuration file for go-test-coverage
# https://github.com/vladopajic/go-test-coverage

# (mandatory) 
# Path to coverprofile file (output of `go test -coverprofile` command)
profile: build/_test_coverage/coverage_all.out

# (optional) 
# When specified reported file paths will not contain local prefix in the output
local-prefix: "github.com/kube-logging/logging-operator"
