# this makefile was generated by
include Makefile.app

OS = $(shell uname | tr A-Z a-z)

# Image URL to use all building/pushing image targets
IMG ?= controller:latest
# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
CRD_OPTIONS ?= "crd:trivialVersions=true,preserveUnknownFields=false,maxDescLen=0"

KUBEBUILDER_VERSION = 2.3.1
LICENSEI_VERSION = v0.3.1
VERSION := $(shell git describe --abbrev=0 --tags)
DOCKER_IMAGE = banzaicloud/logging-operator
DOCKER_TAG ?= ${VERSION}
GOFILES_NOVENDOR = $(shell find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./client/*")
GOFILES_NOPLUGINS =  $(shell find . -type f -name '*.go' -not -path "./pkg/sdk/model/filter/*"  -not -path "./pkg/sdk/model/output/*"  -not -path "./pkg/sdk/model/input/*")
PKGS=$(shell go list ./... | grep -v /vendor)

CONTROLLER_GEN_VERSION = v0.5.0
CONTROLLER_GEN = $(PWD)/bin/controller-gen

GOLANGCI_VERSION = v1.33.0
GOBIN_VERSION = 0.0.13

export KUBEBUILDER_ASSETS := $(PWD)/bin
export PATH := $(PWD)/bin:$(PATH)

all: manager

# Generate docs
.PHONY: docs
docs:
	go run cmd/docs.go

.PHONY: lint
lint: bin/golangci-lint ## Run linter
	bin/golangci-lint run
	cd pkg/sdk && ../../bin/golangci-lint run  -c ../../.golangci.yml

.PHONY: license-check
license-check: bin/licensei ## Run license check
	bin/licensei check
	./scripts/check-header.sh

.PHONY: license-cache
license-cache: bin/licensei ## Generate license cache
	bin/licensei cache

.PHONY: lint-fix
lint-fix: bin/golangci-lint ## Run linter
	bin/golangci-lint run --fix
	cd pkg/sdk && golangci-lint run -c ../../.golangci.yml --fix

bin/gobin: bin/gobin-${GOBIN_VERSION}
	@ln -sf gobin-${GOBIN_VERSION} bin/gobin
bin/gobin-${GOBIN_VERSION}:
	@mkdir -p bin
	curl -L https://github.com/myitcv/gobin/releases/download/v${GOBIN_VERSION}/${OS}-amd64 > ./bin/gobin-${GOBIN_VERSION} && chmod +x ./bin/gobin-${GOBIN_VERSION}

# Run tests
test: generate fmt vet manifests bin/kubebuilder
	@which kubebuilder
	@which etcd
	cd pkg/sdk && go test ./...
	go test ./controllers/... ./pkg/... -coverprofile cover.out -v

# Build manager binary
manager: generate fmt vet
	go build -o bin/manager main.go

# Run against the configured Kubernetes cluster in ~/.kube/config
run: generate fmt vet
	go run ./main.go --verbose --pprof

# remote debug
debug: manager
	dlv --listen=:40000 --log --headless=true --api-version=2 exec bin/manager -- $(ARGS)

# Install CRDs into a cluster
install: manifests
	kubectl apply -f config/crd/bases

# Deploy controller in the configured Kubernetes cluster in ~/.kube/config
deploy: manifests
	kubectl apply -f config/crd/bases
	kustomize build config/default | kubectl apply -f -

# Generate manifests e.g. CRD, RBAC etc.
manifests: bin/controller-gen
	cd pkg/sdk && $(CONTROLLER_GEN) $(CRD_OPTIONS) webhook paths="./..." output:crd:artifacts:config=../../config/crd/bases output:webhook:artifacts:config=../../config/webhook
	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role paths="./controllers/..." output:rbac:artifacts:config=./config/rbac
	cp config/crd/bases/* charts/logging-operator/crds/
	echo "{{- if .Values.rbac.enabled }}" > ./charts/logging-operator/templates/clusterrole.yaml && cat config/rbac/role.yaml |sed -e 's@manager-role@{{ template "logging-operator.fullname" . }}@' | cat >> ./charts/logging-operator/templates/clusterrole.yaml && echo "{{- end }}" >> ./charts/logging-operator/templates/clusterrole.yaml

# Run go fmt against code
fmt:
	go fmt ./...
	cd pkg/sdk && go fmt ./...

# Run go vet against code
vet:
	go vet ./...
	cd pkg/sdk && go vet ./...

# Generate code
generate: bin/controller-gen
	cd pkg/sdk && $(CONTROLLER_GEN) object:headerFile=./../../hack/boilerplate.go.txt paths=./api/...
	cd pkg/sdk && $(CONTROLLER_GEN) object:headerFile=./../../hack/boilerplate.go.txt paths=./model/...
	cd pkg/sdk && $(CONTROLLER_GEN) object:headerFile=./../../hack/boilerplate.go.txt paths=./resourcebuilder/...
	cd pkg/sdk && go generate ./static

# Build the docker image
docker-build:
	docker build . -t ${IMG}
	@echo "updating kustomize image patch file for manager resource"
	sed -i'' -e 's@image: .*@image: '"${IMG}"'@' ./config/default/manager_image_patch.yaml

# Push the docker image
docker-push:
	docker push ${IMG}

bin/controller-gen: | bin/controller-gen_${CONTROLLER_GEN_VERSION} bin
	ln -sf controller-gen_${CONTROLLER_GEN_VERSION} $@

bin/controller-gen_${CONTROLLER_GEN_VERSION}: | bin
	find $(PWD)/bin -name 'controller-gen*' -exec rm {} +
	GOBIN=$(PWD)/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@${CONTROLLER_GEN_VERSION}
	mv $(PWD)/bin/controller-gen $@

bin/golangci-lint: | bin/golangci-lint_${GOLANGCI_VERSION} bin
	ln -sf golangci-lint_${GOLANGCI_VERSION} bin/golangci-lint

bin/golangci-lint_${GOLANGCI_VERSION}: | bin
	find $(PWD)/bin -name 'golangci-lint*' -exec rm {} +
	GOBIN=$(PWD)/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_VERSION}
	mv bin/golangci-lint $@

bin/kubebuilder: | bin/kube-apiserver bin/etcd bin/kubectl bin/kubebuilder_${KUBEBUILDER_VERSION} bin
	ln -sf kubebuilder_${KUBEBUILDER_VERSION}/kubebuilder $@

bin/kube-apiserver: | bin/kubebuilder_${KUBEBUILDER_VERSION} bin
	ln -sf kubebuilder_${KUBEBUILDER_VERSION}/kube-apiserver $@

bin/etcd: | bin/kubebuilder_${KUBEBUILDER_VERSION} bin
	ln -sf kubebuilder_${KUBEBUILDER_VERSION}/etcd $@

bin/kubectl: | bin/kubebuilder_${KUBEBUILDER_VERSION} bin
	ln -sf kubebuilder_${KUBEBUILDER_VERSION}/kubectl $@

bin/kubebuilder_${KUBEBUILDER_VERSION}: | bin
	find $(PWD)/bin -name 'kubebuilder_*' -exec rm -r {} +
	curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KUBEBUILDER_VERSION}/kubebuilder_${KUBEBUILDER_VERSION}_${OS}_amd64.tar.gz | tar xvz -C bin
	ln -sf kubebuilder_${KUBEBUILDER_VERSION}_${OS}_amd64/bin $@

bin/licensei: | bin/licensei_${LICENSEI_VERSION}
	ln -sf licensei_${LICENSEI_VERSION} $@

bin/licensei_${LICENSEI_VERSION}: | bin
	find $(PWD)/bin -name 'licensei*' -exec rm {} +
	curl -sfL https://raw.githubusercontent.com/goph/licensei/master/install.sh | bash -s ${LICENSEI_VERSION}
	mv bin/licensei $@

check-diff: check
	go mod tidy
	$(MAKE) generate manifests
	git diff --exit-code ':(exclude)./ADOPTERS.md' ':(exclude)./docs/*'

tidy:
	find . -iname "go.mod" | xargs -L1 sh -c 'cd $$(dirname $$0); go mod tidy'

bin:
	mkdir -p bin
