apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: defaultlogging
spec:
  fluentd:
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
  fluentbit: {}
  controlNamespace: default
