apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: defaultlogging
spec:
  fluentd:
    disablePvc: true
    fluentOutLogrotate:
      enabled: false
  fluentbit: {}
  controlNamespace: default
