apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: defaultlogging
spec:
  fluentd:
    disablePvc: true
    labels:
      a: b
  fluentbit:
    labels:
      c: d
  controlNamespace: default