apiVersion: v1
kind: Namespace
metadata:
  name: c
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: all
  namespace: c
spec:
  loggingRef: c
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  globalOutputRefs:
    - http
