apiVersion: v1
kind: Namespace
metadata:
  name: a
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: all
  namespace: a
spec:
  loggingRef: a
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  globalOutputRefs:
    - http
