apiVersion: v1
kind: Namespace
metadata:
  name: b-control
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: b
spec:
  loggingRef: b
  fluentd:
    nodeSelector:
      tenant: tenant-b
  controlNamespace: b-control
  watchNamespaceSelector:
    matchLabels:
      tenant: tenant-b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: b
spec:
  loggingRef: b
  nodeSelector:
    tenant: tenant-b
