apiVersion: v1
kind: Namespace
metadata:
  name: a-control
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: a
spec:
  loggingRef: a
  fluentd:
    nodeSelector:
      tenant: tenant-a
  controlNamespace: a-control
  watchNamespaceSelector:
    matchLabels:
      tenant: tenant-a
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: a
spec:
  loggingRef: a
  nodeSelector:
    tenant: tenant-a
