apiVersion: v1
kind: Namespace
metadata:
  name: b
  labels:
    tenant: tenant-b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: all
  namespace: b
spec:
  loggingRef: b
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  localOutputRefs:
    - http
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: http
  namespace: b
spec:
  loggingRef: b
  http:
    endpoint: http://test-receiver.infra:8080/tenant-b
    content_type: application/json
    buffer:
      type: memory
      timekey: 1s
      timekey_wait: 0s
