apiVersion: v2
type: application
name: logging-operator
version: 4.1.0
appVersion: 4.1.0
kubeVersion: ">=1.16.0-0"
description: Logging operator for Kubernetes based on Fluentd and Fluentbit.
keywords:
  - logging
  - fluentd
  - fluentbit
home: https://kube-logging.github.io
sources:
  - https://github.com/kube-logging/logging-operator
  - https://github.com/kube-logging/helm-charts/tree/main/charts/logging-operator
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Moved to to location
  artifacthub.io/images: |
    - name: logging-operator
      image: ghcr.io/kube-logging/logging-operator:4.0.0
