{{- if .Values.tls.enabled }}
{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $cn := printf "%s-%s.%s.svc%s" (include "logging-operator-logging.name" .) "fluentd" .Release.Namespace (include "logging-operator-logging.clusterDomainAsSuffix" .) }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}
{{ $client := genSignedCert "" nil nil 365 $ca }}

{{- if not .Values.tls.fluentdSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logging-operator-logging.name" . }}-fluentd-tls
  labels:
{{ include "logging-operator-logging.labels" . | indent 4 }}
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
{{ end }}

---

{{- if not .Values.tls.fluentbitSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logging-operator-logging.name" . }}-fluentbit-tls
  labels:
{{ include "logging-operator-logging.labels" . | indent 4 }}
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $client.Cert }}
  tls.key: {{ b64enc $client.Key }}
{{ end }}
{{ end }}
