apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-log-to-s3
  namespace: logging
spec:
  filters:
    - tag_normaliser: {}
  selectors: {}
  globalOutputRefs:
    - s3-output
