apiVersion: v1
kind: Namespace
metadata:
  name: customer-b
  labels:
    tenant: customer-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: customer-b-infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: customer-b
  labels:
    tenant: customer-b
spec:
  fluentd: {}
  controlNamespace: customer-b-infra
  watchNamespaceSelector:
    matchLabels:
      tenant: customer-b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: http
  namespace: customer-b
spec:
  http:
    endpoint: http://test-receiver.infra:8080/customer-b
    content_type: application/json
    buffer:
      type: memory
      timekey: 1s
      timekey_wait: 0s
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: log-generator
  namespace: customer-b
spec:
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  localOutputRefs:
    - http
