apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: all-to-file
spec:
  configCheck:
    strategy: StartWithTimeout
    timeoutSeconds: 5
  fluentd: {}
  controlNamespace: default
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: all
spec:
  filters:
    - tag_normaliser: {}
  match:
    - select: {}
  localOutputRefs:
    - nullout
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: nullout
spec:
  nullout: {}
