apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: defaultlogging
spec:
  fluentd:
    disablePvc: true
    resources:
      requests:
        cpu: 0
        memory: 0
  fluentbit: {}
  controlNamespace: default
