apiVersion: v1
kind: Namespace
metadata:
  name: customer-b
  labels:
    tenant: customer-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: customer-b-infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: customer-b
  labels:
    tenant: customer-b
spec:
  fluentd:
    disablePvc: true
    logLevel: trace
  controlNamespace: customer-b-infra
  watchNamespaceSelector:
    matchLabels:
      tenant: customer-b
  routeConfig:
    enableTelemetryControllerRoute: true
    disableLoggingRoute: true
    tenantLabels:
      matchLabels:
        tenant: customer-b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all
  namespace: customer-b
spec:
  match:
  - select:
      labels:
        app.kubernetes.io/name: log-generator
  globalOutputRefs:
    - http-b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: http-b
  namespace: customer-b
spec:
  http:
    endpoint: http://logging-operator-test-receiver:8080
    content_type: application/json
    buffer:
      type: memory
      tags: time
      timekey: 1s
      timekey_wait: 0s
