//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright © 2020 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/cisco-open/operator-tools/pkg/types"
	"github.com/kube-logging/logging-operator/pkg/sdk/extensions/api/tailer"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTailer) DeepCopyInto(out *EventTailer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTailer.
func (in *EventTailer) DeepCopy() *EventTailer {
	if in == nil {
		return nil
	}
	out := new(EventTailer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventTailer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTailerList) DeepCopyInto(out *EventTailerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventTailer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTailerList.
func (in *EventTailerList) DeepCopy() *EventTailerList {
	if in == nil {
		return nil
	}
	out := new(EventTailerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventTailerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTailerSpec) DeepCopyInto(out *EventTailerSpec) {
	*out = *in
	in.PositionVolume.DeepCopyInto(&out.PositionVolume)
	if in.WorkloadMetaBase != nil {
		in, out := &in.WorkloadMetaBase, &out.WorkloadMetaBase
		*out = new(types.MetaBase)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadBase != nil {
		in, out := &in.WorkloadBase, &out.WorkloadBase
		*out = new(types.PodSpecBase)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerBase != nil {
		in, out := &in.ContainerBase, &out.ContainerBase
		*out = new(types.ContainerBase)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(tailer.ImageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTailerSpec.
func (in *EventTailerSpec) DeepCopy() *EventTailerSpec {
	if in == nil {
		return nil
	}
	out := new(EventTailerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTailerStatus) DeepCopyInto(out *EventTailerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTailerStatus.
func (in *EventTailerStatus) DeepCopy() *EventTailerStatus {
	if in == nil {
		return nil
	}
	out := new(EventTailerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileTailer) DeepCopyInto(out *FileTailer) {
	*out = *in
	if in.ContainerBase != nil {
		in, out := &in.ContainerBase, &out.ContainerBase
		*out = new(types.ContainerBase)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(tailer.ImageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileTailer.
func (in *FileTailer) DeepCopy() *FileTailer {
	if in == nil {
		return nil
	}
	out := new(FileTailer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostTailer) DeepCopyInto(out *HostTailer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostTailer.
func (in *HostTailer) DeepCopy() *HostTailer {
	if in == nil {
		return nil
	}
	out := new(HostTailer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostTailer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostTailerList) DeepCopyInto(out *HostTailerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostTailer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostTailerList.
func (in *HostTailerList) DeepCopy() *HostTailerList {
	if in == nil {
		return nil
	}
	out := new(HostTailerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostTailerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostTailerSpec) DeepCopyInto(out *HostTailerSpec) {
	*out = *in
	if in.FileTailers != nil {
		in, out := &in.FileTailers, &out.FileTailers
		*out = make([]FileTailer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemdTailers != nil {
		in, out := &in.SystemdTailers, &out.SystemdTailers
		*out = make([]SystemdTailer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkloadMetaBase != nil {
		in, out := &in.WorkloadMetaBase, &out.WorkloadMetaBase
		*out = new(types.MetaBase)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadBase != nil {
		in, out := &in.WorkloadBase, &out.WorkloadBase
		*out = new(types.PodSpecBase)
		(*in).DeepCopyInto(*out)
	}
	in.Image.DeepCopyInto(&out.Image)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostTailerSpec.
func (in *HostTailerSpec) DeepCopy() *HostTailerSpec {
	if in == nil {
		return nil
	}
	out := new(HostTailerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostTailerStatus) DeepCopyInto(out *HostTailerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostTailerStatus.
func (in *HostTailerStatus) DeepCopy() *HostTailerStatus {
	if in == nil {
		return nil
	}
	out := new(HostTailerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemdTailer) DeepCopyInto(out *SystemdTailer) {
	*out = *in
	if in.ContainerBase != nil {
		in, out := &in.ContainerBase, &out.ContainerBase
		*out = new(types.ContainerBase)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(tailer.ImageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemdTailer.
func (in *SystemdTailer) DeepCopy() *SystemdTailer {
	if in == nil {
		return nil
	}
	out := new(SystemdTailer)
	in.DeepCopyInto(out)
	return out
}
