name: CI

on:
  push:
    branches:
      - master
      - "release-[0-9]+.[0-9]+*"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: '.go-version'

      - name: Check diff
        run: make check-diff

      - name: Test
        run: make test

      - name: Generate test coverage
        run: make generate-test-coverage

      - name: Test Coverage
        uses: vladopajic/go-test-coverage@f94bcf0d6b9fa5fb8b783830b22648f6c17475e2 # v2.19.0
        with:
          config: ./.testcoverage.yml
          source-dir: ./

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: '.go-version'

      - name: Lint
        run: make lint
        env:
          LINTER_FLAGS: '--timeout 5m'

  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: '.go-version'

      - name: Cache licenses
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: licensei-v2-${{ hashFiles('go.sum') }}
          path: |
            .licensei.cache
          restore-keys: |
            licensei-v2

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make license-cache

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make license-check

  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      version: "latest"
      publish: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

  dependency-images:
    name: Dependency images
    uses: ./.github/workflows/dependency-images.yaml
    with:
      publish: ${{ github.event_name == 'push' }}
      fluentd-image-types: "full"
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
